import os
import io
import zipfile
import json
import re
import requests
from dotenv import load_dotenv
from google import genai
from google.genai import types

# Load environment variables
load_dotenv()

# Initialize Gemini client
# Note: Client will automatically pick up GEMINI_API_KEY from the environment.
# If not present, we will gracefully handle it during pipeline execution.
def get_gemini_client():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("Missing GEMINI_API_KEY inside environment configuration.")
    return genai.Client(api_key=api_key)

def deploy_to_netlify(js_content: str) -> dict:
    """
    Creates a ZIP archive in memory containing index.html with the React/Babel/Tailwind bundle
    and posts it directly to Netlify's site creation API endpoint.
    """
    token = os.getenv("NETLIFY_AUTH_TOKEN")
    if not token:
        return {"status": "Error", "message": "Missing NETLIFY_AUTH_TOKEN in environment variables."}

    # Define HTML Template with CDN dependencies
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Generated React App</title>
    <!-- React and ReactDOM CDN -->
    <script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>
    <!-- Babel standalone compiler for JSX in browser -->
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- FontAwesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        /* Custom scrollbar and subtle transitions */
        ::-webkit-scrollbar {{
            width: 8px;
        }}
        ::-webkit-scrollbar-track {{
            background: #f1f1f1;
        }}
        ::-webkit-scrollbar-thumb {{
            background: #cbd5e1;
            border-radius: 4px;
        }}
        ::-webkit-scrollbar-thumb:hover {{
            background: #94a3b8;
        }}
    </style>
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen">
    <div id="root"></div>
    <script type="text/babel">
        {js_content}
    </script>
</body>
</html>"""

    # Create ZIP in-memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.writestr("index.html", html_template)
    
    zip_data = zip_buffer.getvalue()

    # Upload to Netlify site creation endpoint
    # This endpoint creates a new site with the provided files in one call.
    url = "https://api.netlify.com/api/v1/sites"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/zip"
    }

    try:
        response = requests.post(url, headers=headers, data=zip_data, timeout=45)
        if response.status_code in [200, 201]:
            data = response.json()
            site_url = data.get("ssl_url") or data.get("url")
            site_id = data.get("id")
            return {
                "status": "Success",
                "url": site_url,
                "site_id": site_id,
                "message": "Application successfully deployed to production."
            }
        else:
            return {
                "status": "Error",
                "message": f"Netlify Deployment failed (HTTP {response.status_code})",
                "details": response.text
            }
    except Exception as e:
        return {
            "status": "Error",
            "message": f"An exception occurred during deployment: {str(e)}"
        }

def clean_code(code_str: str) -> str:
    """Removes markdown code blocks if generated by the LLM."""
    code_str = code_str.strip()
    # Remove markdown fence blocks if present
    code_str = re.sub(r"^```(javascript|jsx|js|html)?\n", "", code_str, flags=re.IGNORECASE)
    code_str = re.sub(r"\n```$", "", code_str)
    return code_str.strip()

def run_agent_pipeline(user_prompt: str, callback=None) -> dict:
    """
    Coordinates the multi-agent pipeline:
    1. Product Architect maps structure.
    2. React Coder generates JS.
    3. Quality Linter verifies and self-heals code.
    4. DevOps Deployer deploys to Netlify.
    """
    def log(step: str, message: str, details: str = None, success: bool = True):
        if callback:
            callback(step, {"message": message, "details": details, "success": success})

    try:
        client = get_gemini_client()
    except Exception as e:
        log("init", str(e), success=False)
        return {"status": "Error", "message": str(e)}

    # --- AGENT 1: PRODUCT ARCHITECT ---
    log("architect", "Product Architect is analyzing requirements & building components...")
    
    architect_system_prompt = (
        "You are an expert Systems Architect specializing in React applications. "
        "Your task is to take a raw user concept and outline a component hierarchy tree. "
        "Identify necessary state structures, state hooks, and data layout flows. "
        "Ensure you specify interactive event flows (buttons, inputs) using Tailwind classes."
    )
    
    try:
        architect_res = client.models.generate_content(
            model='gemini-2.5-pro',
            contents=f"User Concept: {user_prompt}",
            config=types.GenerateContentConfig(
                system_instruction=architect_system_prompt,
                temperature=0.2
            )
        )
        blueprint = architect_res.text
        log("architect", "Product Architect generated blueprint.", blueprint)
    except Exception as e:
        log("architect", f"Failed in Architect phase: {str(e)}", success=False)
        return {"status": "Error", "message": f"Architect Agent failed: {str(e)}"}

    # --- AGENT 2 & 3: REACT CODER & QUALITY LINTER (Self-Healing Loop) ---
    coder_system_prompt = (
        "You are an expert Frontend Developer. Review the provided architecture blueprint.\n"
        "Generate a single-file interactive React 18 component.\n"
        "Requirements:\n"
        "1. Do not use external import statements for React or ReactDOM (they are loaded globally from CDN). Use React.useState, React.useEffect, etc.\n"
        "2. Use inline Tailwind CSS classes for layout, colors, and responsive designs. Be visual, premium, and dynamic.\n"
        "3. Incorporate FontAwesome icons (using <i class=\"fas fa-...\"> or similar) for UI elements.\n"
        "4. Make the app highly interactive, using rich state, smooth transitions, and premium visuals (gradients, cards, dark mode options, micro-interactions).\n"
        "5. Target mounting directly to the DOM at:\n"
        "   const root = ReactDOM.createRoot(document.getElementById('root'));\n"
        "   root.render(<App />);\n\n"
        "Do not wrap your output in markdown code blocks. Output ONLY the raw javascript code."
    )

    linter_system_prompt = (
        "You are a strict JavaScript/React code validator.\n"
        "Your task is to analyze the provided code for syntax errors, bracket mismatches, unclosed HTML tags, incorrect React state hooks usage (like using useState instead of React.useState since React is loaded globally), or missing variables.\n"
        "Return your evaluation in JSON format with the following schema:\n"
        "{\n"
        "  \"is_valid\": boolean,\n"
        "  \"errors\": [\n"
        "    {\n"
        "      \"line_number\": integer or null,\n"
        "      \"error_message\": \"detailed description of the error\",\n"
        "      \"context\": \"code snippet around the error\"\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "Do not include any other markdown wrapper or explanations. Return ONLY the JSON object."
    )

    log("coder", "React Coder is writing application code...")
    try:
        coder_res = client.models.generate_content(
            model='gemini-2.5-pro',
            contents=f"Generate the React application based on this blueprint:\n\n{blueprint}",
            config=types.GenerateContentConfig(
                system_instruction=coder_system_prompt,
                temperature=0.1
            )
        )
        js_code = clean_code(coder_res.text)
        log("coder", "React Coder generated initial code.", js_code)
    except Exception as e:
        log("coder", f"Failed in React Coder initial phase: {str(e)}", success=False)
        return {"status": "Error", "message": f"React Coder Agent failed: {str(e)}"}

    # Self-Healing Loop
    max_lint_attempts = 3
    current_attempt = 1
    code_is_valid = False

    while current_attempt <= max_lint_attempts:
        log("linter", f"Quality Linter checking code (Attempt {current_attempt}/{max_lint_attempts})...")
        
        try:
            linter_res = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=f"Validate this React code:\n\n{js_code}",
                config=types.GenerateContentConfig(
                    system_instruction=linter_system_prompt,
                    response_mime_type="application/json",
                    temperature=0.1
                )
            )
            
            lint_result = json.loads(linter_res.text.strip())
            
            if lint_result.get("is_valid", True):
                code_is_valid = True
                log("linter", "Quality Linter passed code validation!", json.dumps(lint_result, indent=2))
                break
            else:
                errors_str = json.dumps(lint_result.get("errors", []), indent=2)
                log("linter", f"Quality Linter found errors in code (Attempt {current_attempt})", errors_str, success=False)
                
                # Ask Coder to fix the errors
                log("coder", f"React Coder self-healing loop: Fixing compilation issues (Attempt {current_attempt})...")
                coder_correction_prompt = (
                    f"The Quality Linter found the following errors in your code:\n{errors_str}\n\n"
                    f"Please modify and fix the code. Ensure all global variables are correctly resolved and brackets/tags are closed.\n"
                    f"Original code:\n{js_code}"
                )
                
                coder_res = client.models.generate_content(
                    model='gemini-2.5-pro',
                    contents=coder_correction_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=coder_system_prompt,
                        temperature=0.1
                    )
                )
                js_code = clean_code(coder_res.text)
                log("coder", f"React Coder generated corrected code (Attempt {current_attempt}).", js_code)
                current_attempt += 1

        except Exception as e:
            log("linter", f"Linter error or exception: {str(e)}. Continuing with deployment.", success=False)
            # If the linter crashes or runs into quota issues, we proceed rather than failing the whole app
            code_is_valid = True
            break

    # --- AGENT 4: DEVOPS DEPLOYER ---
    log("deployer", "DevOps Deployer is packaging site bundles & sending to Netlify...")
    
    deploy_res = deploy_to_netlify(js_code)
    
    if deploy_res.get("status") == "Success":
        log("deployer", "DevOps Deployer successfully published the application!", deploy_res["url"])
        return {
            "status": "Success",
            "url": deploy_res["url"],
            "site_id": deploy_res.get("site_id"),
            "code": js_code
        }
    else:
        log("deployer", f"Deployment failed: {deploy_res.get('message')}", deploy_res.get("details"), success=False)
        return {
            "status": "Error",
            "message": deploy_res.get("message"),
            "details": deploy_res.get("details")
        }
